<a href="https://colab.research.google.com/github/DushyantKhinchi/Cosine_-_Jaccard_Document_Similarities/blob/master/Cosine_%26_Jaccard_Document_Similarities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing Google Drive to access Dataset
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
#Checking if the files are available
!ls "drive/Shared drives/IDS 576/HW1"

ls: cannot access 'drive/Shared drives/IDS 576/HW1': No such file or directory


In [ ]:
#importing dependencies
import nltk
nltk.download('punkt') # first-time use only
nltk.download('stopwords')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#function for creating tokens
def tokenize(file_path):
  #load data
  file = open(file_path, 'rt')
  text = file.read()
  file.close()
  # split into words
  tokens = nltk.word_tokenize(text)
  return tokens

In [ ]:
#function to remove punctuation
def remove_punctuation(tokens):
  words = [word for word in tokens if word.isalpha()]
  return words

In [ ]:
#change to lower case
def lower_case(tokens):
  tokens_lc=[w.lower() for w in tokens]
  return tokens_lc

In [ ]:
#remove stopwords
from nltk.corpus import stopwords
def rm_stopwords(words):
  stop_words = set(stopwords.words('english'))
  words = [w for w in words if not w in stop_words]
  return words

In [ ]:
#function for stemming
def stem(words):
  porter = nltk.PorterStemmer()
  stemmed = [porter.stem(word) for word in words]
  return stemmed

In [ ]:
#function to calcuate jaccard similarity
def jaccard_sim(str1, str2): 
    a = set(str1) 
    b = set(str2)
    c = a.intersection(b)
    return float(len(c)) / (len(a) + len(b) - len(c))

In [ ]:
#tokenizing
tokens_mit = tokenize('drive/Shared drives/Adv Text Homework/HW1/MIT.txt')
#removing punctuations 
words_mit = remove_punctuation(tokens_mit)
#converting to lower case
words_mit=lower_case(words_mit)
#remove stop words
words_mit=rm_stopwords(words_mit)
#stemming
stemmed_words_mit = stem(words_mit)

In [ ]:
tokens_stanford = tokenize('drive/Shared drives/Adv Text Homework/HW1/Stanford.txt')
words_stanford = remove_punctuation(tokens_stanford)
words_stanford=lower_case(words_stanford)
words_stanford=rm_stopwords(words_stanford)
stemmed_words_stanford = stem(words_stanford)

In [ ]:
tokens_uic = tokenize('drive/Shared drives/Adv Text Homework/HW1/UIC.txt')
words_uic = remove_punctuation(tokens_uic)
words_uic=lower_case(words_uic)
words_uic=rm_stopwords(words_uic)
stemmed_words_uic = stem(words_uic)

In [ ]:
tokens_tesla = tokenize('drive/Shared drives/Adv Text Homework/HW1/Tesla.txt')
words_tesla = remove_punctuation(tokens_tesla)
words_tesla=lower_case(words_tesla)
words_tesla=rm_stopwords(words_tesla)
stemmed_words_tesla = stem(words_tesla)

In [ ]:
tokens_uis = tokenize('drive/Shared drives/Adv Text Homework/HW1/UIS.txt')
words_uis = remove_punctuation(tokens_uis)
words_uis=lower_case(words_uis)
words_uis=rm_stopwords(words_uis)
stemmed_words_uis = stem(words_uis)

In [ ]:
tokens_uiuc = tokenize('drive/Shared drives/Adv Text Homework/HW1/UIUC.txt')
words_uiuc = remove_punctuation(tokens_uiuc)
words_uiuc=lower_case(words_uiuc)
words_uiuc=rm_stopwords(words_uiuc)
stemmed_words_uiuc = stem(words_uiuc)

In [ ]:
jaccard_dist_mit = jaccard_sim(stemmed_words_uic,stemmed_words_mit)
jaccard_dist_mit

0.21244635193133046

In [ ]:
jaccard_dist_stanford = jaccard_sim(stemmed_words_uic,stemmed_words_stanford)
jaccard_dist_stanford

0.2611464968152866

In [ ]:
jaccard_dist_tesla = jaccard_sim(stemmed_words_uic,stemmed_words_tesla)
jaccard_dist_tesla

0.19028062970568105

In [ ]:
jaccard_dist_uis = jaccard_sim(stemmed_words_uic,stemmed_words_uis)
jaccard_dist_uis

0.2372611464968153

In [ ]:
jaccard_dist_uiuc = jaccard_sim(stemmed_words_uic,stemmed_words_uiuc)
jaccard_dist_uiuc

0.2837528604118993

In [ ]:
# Reading files
def file_input(file_path):
  file=open(file_path, mode="rt")
  text=file.read()
  file.close()
  return text

In [ ]:
stanford=file_input('drive/Shared drives/Adv Text Homework/HW1/Stanford.txt')
uic=file_input('drive/Shared drives/Adv Text Homework/HW1/UIC.txt')
mit=file_input('drive/Shared drives/Adv Text Homework/HW1/MIT.txt')
tesla=file_input('drive/Shared drives/Adv Text Homework/HW1/Tesla.txt')
uis=file_input('drive/Shared drives/Adv Text Homework/HW1/UIS.txt')
uiuc=file_input('drive/Shared drives/Adv Text Homework/HW1/UIUC.txt')


In [ ]:
documents=[stanford, uic, mit, tesla, uis, uiuc]

In [ ]:
 #normalize by lemmatization
 import numpy, string
 nltk.download('wordnet') # first-time use only
 lemmer = nltk.stem.WordNetLemmatizer()
 def LemTokens(tokens):
     return [lemmer.lemmatize(token) for token in tokens]
 remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
 def LemNormalize(text):
     return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [ ]:
#Turn text into tf vectors
from sklearn.feature_extraction.text import CountVectorizer
LemVectorizer = CountVectorizer(tokenizer=LemNormalize, stop_words='english')
LemVectorizer.fit_transform(documents)

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


<6x10423 sparse matrix of type '<class 'numpy.int64'>'
	with 15986 stored elements in Compressed Sparse Row format>

In [ ]:
#Corpus Vocabulary
LemVectorizer.vocabulary_

{'stanford': 8981,
 'university': 9763,
 'wikipedia': 10181,
 'free': 4677,
 'encyclopedia': 4162,
 'jump': 5745,
 'navigationjump': 6801,
 'search': 8540,
 'redirects': 8009,
 'disambiguation': 3818,
 'leland': 6023,
 'junior': 5750,
 'seal': 8537,
 '2003svg': 627,
 'motto': 6691,
 'german': 4814,
 'die': 3783,
 'luft': 6209,
 'der': 3735,
 'freiheit': 4684,
 'weht1': 10124,
 'english': 4197,
 'wind': 10199,
 'freedom': 4678,
 'blows1': 2502,
 'type': 9679,
 'private': 7647,
 'research': 8175,
 'established': 4253,
 '189123': 344,
 'founder': 4646,
 'jane': 5664,
 'endowment': 4172,
 '277': 1114,
 'billion': 2446,
 '20194': 991,
 'budget': 2644,
 '65': 1443,
 '2018–195': 953,
 'president': 7605,
 'marc': 6316,
 'tessierlavigne': 9403,
 'provost': 7767,
 'persis': 7358,
 'drell': 3947,
 'academic': 1694,
 'staff': 8967,
 '22406': 1038,
 'administrative': 1783,
 '125087': 162,
 'excluding': 4307,
 'shc': 8684,
 'student': 9108,
 '17249': 277,
 'fall': 4418,
 '20198': 995,
 'undergraduat

In [ ]:
#tf Matrix
tf_matrix=LemVectorizer.transform(documents).toarray()
print(tf_matrix)

#tf_matrix.shape

[[1 0 1 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [1 1 0 ... 1 1 1]
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [ ]:
#Calculating idf
from sklearn.feature_extraction.text import TfidfTransformer
tfidftrans=TfidfTransformer(norm="l2")
tfidftrans.fit(tf_matrix)
print(tfidftrans.idf_)

[1.55961579 2.25276297 2.25276297 ... 2.25276297 2.25276297 1.15415068]


In [ ]:
#tf-idf matrix
tfidf_matrix=tfidftrans.transform(tf_matrix)
print(tfidf_matrix.toarray())

[[0.00158332 0.         0.002287   ... 0.         0.         0.00117169]
 [0.         0.         0.         ... 0.         0.         0.00361325]
 [0.00138049 0.00199403 0.         ... 0.00199403 0.00199403 0.0010216 ]
 [0.00081547 0.         0.         ... 0.         0.         0.00060346]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.00217861]]


In [ ]:
#Cosine similarity matrix
cosine_sim_matrix=(tfidf_matrix*tfidf_matrix.T).toarray() #multiplying tfidf_matrix with its transpose
print(cosine_sim_matrix)

#Cosine similarity of the following with UIC
#Stanford:0.304
#MIT:0.241
#Tesla:0.127
#UIS:0.478
#UIUC:0.681

[[1.         0.30455801 0.17835885 0.11274273 0.22845563 0.36795099]
 [0.30455801 1.         0.24141374 0.12795028 0.47829801 0.68178035]
 [0.17835885 0.24141374 1.         0.09601026 0.15360688 0.28944901]
 [0.11274273 0.12795028 0.09601026 1.         0.06244378 0.16230252]
 [0.22845563 0.47829801 0.15360688 0.06244378 1.         0.60517772]
 [0.36795099 0.68178035 0.28944901 0.16230252 0.60517772 1.        ]]


In [ ]:
#Alternative method using tfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
def cos_similarity(textlist):
    tfidf = TfidfVec.fit_transform(textlist)
    return (tfidf * tfidf.T).toarray()
cos_similarity(documents)

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


array([[1.        , 0.30455801, 0.17835885, 0.11274273, 0.22845563,
        0.36795099],
       [0.30455801, 1.        , 0.24141374, 0.12795028, 0.47829801,
        0.68178035],
       [0.17835885, 0.24141374, 1.        , 0.09601026, 0.15360688,
        0.28944901],
       [0.11274273, 0.12795028, 0.09601026, 1.        , 0.06244378,
        0.16230252],
       [0.22845563, 0.47829801, 0.15360688, 0.06244378, 1.        ,
        0.60517772],
       [0.36795099, 0.68178035, 0.28944901, 0.16230252, 0.60517772,
        1.        ]])